default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: "<%= ENV['MYSQL_ENV_MYSQL_DATABASE'] || "islandzero" %>"
  pool: 5
  username: "<%= ENV['MYSQL_ENV_MYSQL_USER']     || "islandzero" %>"
  password: "<%= ENV['MYSQL_ENV_MYSQL_PASSWORD'] || "islandzero" %>"
  host:     "<%= ENV['MYSQL_PORT_3306_TCP_ADDR'] || "127.0.0.1" %>"
  port:      <%= ENV['MYSQL_PORT_3306_TCP_PORT'] || 3306 %>
